export const ChangeApiKey = 'Change API key'
export const ClearChat = 'Clear Chat'
export const CreatingToken = 'Creating token'
export const FailedToClearOpenAiApiKey = 'Failed to clear OpenAI API key.'
export const FailedToCreateToken = 'Failed to create token.'
export const FailedToCreateTokenWithDetails =
  'Failed to create token. Check your network and API key.'
export const FundedVoiceClosed =
  'The backend-funded voice connection closed. Start again to reconnect.'
export const FundedVoiceUnavailable = 'Backend-funded voice is unavailable.'
export const FailedToSaveOpenAiApiKey = 'Failed to save OpenAI API key.'
export const GptVoice = 'Gpt Voice'
export const GptVoiceDisplayName = 'GptVoice'
export const Idle = 'idle'
export const InProgress = 'In Progress'
export const InvalidOpenAiApiKey = 'OpenAI API key is invalid (401/403).'
export const InvalidOpenAiApiKeyFormat = 'OpenAI API key format looks invalid.'
export const MissingOpenAiApiKey = 'NO_API_KEY: OpenAI API key is not set.'
export const MissingOpenAiApiKeyPrompt =
  'NO_API_KEY: Add your OpenAI API key above to start.'
export const NetworkFailure =
  'Network failure while creating token. Retry and check your internet connection.'
export const OpenAiApiKeyRequired = 'OpenAI API key is required.'
export const OpenAiApiKeyRequiredForVoice =
  'OpenAI API key required to start a live voice session.'
export const RealtimeMiniModel = 'Model: Realtime 2.1 mini (cheaper)'
export const RealtimeStandardModel = 'Model: Realtime 2.1 (better quality)'
export const SaveApiKey = 'Save API key'
export const Saving = 'Saving...'
export const SavingKey = 'Saving key'
export const SetUpOpenAiApiKey = 'Set up your OpenAI API key'
export const StartTalking = 'Start talking'
export const StopTalking = 'Stop talking'
export const MonthlyAllowanceExceeded =
  'Your monthly AI allowance has been used.'
export const UseOwnApiKey = 'Use your own API key'
export const UseBetter = 'Use better'
export const UseCheap = 'Use cheap'
export const WelcomeDescription =
  'Your key is stored in extension secret storage. Press Save to continue.'
